engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
ratings:
  paths:
  - "**.ts"
exclude_paths:
  - coverage
  - dist
  - node_modules
  - typings
