language: node_js
sudo: false
node_js:
- '4.2.6'
before_install:
- npm install -g karma-cli tsd
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass
- npm install -g codeclimate-test-reporter

install:
- npm install

script:
- npm test
after_script:
- codeclimate-test-reporter < .coverage/lcov.info

branches:
  only:
    - master

addons:
    code_climate:
        repo_token: e0e8db1f7a29b103976ea43fa3f581ddf17a1a8f7f2bd55851f5ef772e05b662
