language: node_js
sudo: false
node_js:
- '4.2.6'
before_install:
- npm install -g karma-cli tsd
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- gem install sass

install:
- npm install

script:
- npm test

after_script:
- cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
